version: "3"

services:

  backend:
    depends_on: [database]
    build:
      context: .
      dockerfile: back.Dockerfile
    image: fcbackendimage
    ports: [3333:3333]
    networks: [hackathon]

  frontend:
    depends_on: [backend]
    build:
      context: .
      dockerfile: front.Dockerfile
    image: fcfrontendimage
    ports: [3000:3000]
    networks: [hackathon]

  database:
    image: postgres
    ports: [5432:5432]
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: desafioFC_postgres
    networks: [hackathon]

networks:
  hackathon:
    driver: bridge
